### PR TITLE
Contacts Endpoint - Method to fetch multiple contacts at the same time.

### PR DESCRIPTION
**Pull request by LukeKirbyDG**
Similar to how InvoicesEndpoint has an Ids method to find multiple
Invoices at the same time, this method is for retrieving multiple
contacts at the same time which helps with batching requests and not
hitting the API request limit as quickly when fetching a lot of data, and I've added a unit test for completeness.

### CODE REVIEW

**Comment by LukeKirbyDG** [comment]
I've added this PR because when using the Xero Api wrapper I found that there wasn't an option to pull multiple contacts at the same time but the API itself supported it so I thought it would be a useful thing to have in the api wrapper if this gets merged.

**Comment by DerekHAu** [comment]
any word on this being merged?

**Comment by MJMortimer** [comment]
Thanks for your contribution @DerekHAu, apologies for the delay

**Comment by LukeKirbyDG** [comment]
Thanks @MJMortimer! Any idea roughly when there would be a new release available on nuget with the merged changes? No rush, just curious

**Comment by MJMortimer** [comment]
Within the next hour 🤞

**Pull request merged**
