### PR TITLE
[READY] Authentication refactor

### PR DESCRIPTION
**Pull request by ben-biddington**
**PLEASE DON'T TAKE THIS YET**

## Authentication

It'd be nice to have the library itself know less about authentication implementation.

I have modifed `IAuthenticator` so it now represents a single function: `Authenticate(HttpWebRequest request)`, thereby concealing the details of the authentication mechanism from `HttpClient`.

`HttpClient` and `IAuthenticator` now communciate in terms if HTTP rather than OAuth.

This means that `HttpClient` may be used elsewhere with another authentication type.

## URLS

Have also moved knowledge of full URL path out of core so that it is bound to resource names:

```
/organisation
```

rather than:

```
/api.xro/2.0/organisation
```

This has broken other connections like files because it has a different base path. (Resolved by `aaa356c00f5bd8f00e66062bc0152e6a30a5b250`)

### CODE REVIEW

**Comment by ben-biddington** [comment]
@philals, you're right in thinking we now have conflicts with current master

**Comment by ben-biddington** [comment]
@philals have managed to rebase on current master -- and this one compiles.

**Comment by MJMortimer** [comment]
Cheers BB. We'll take a look Monday

**Comment by ben-biddington** [comment]
Hey @philals @MatthewMXero, I have this up to `master` but build server is failing. Where do I see more detail about that?

**Comment by philals** [comment]
Thanks Ben. We have our jog days next week so will have a good crack at testing the backwards capability. We won't do any more PRs into Master.

**Comment by ben-biddington** [comment]
Sounds grand, lunch's on me

**Comment by ben-biddington** [comment]
Offer expired

**Pull request closed without merging**
