### PR TITLE
Update TaxRate.cs

### PR DESCRIPTION
**Pull request by xmixalis**
Remove the EmitDefaultValue = false form ReportTaxType in TaxRate.cs so that OUTPUT value can be serialized. 
ReportTaxType  is required when creating TaxRates.

### CODE REVIEW

**Comment by philals** [comment]
The problem with this is that if you want to update a TaxRate without supplying the ReportTayType then it will default to the top enum value.

We are thinking that this would be a good 
```
[DataMember(EmitDefaultValue = false)]
public ReportTaxType? ReportTaxType { get; set; }
```
This will mean that the default value will be null and won't need to be set.

Will this work for you?

**Comment by xmixalis** [comment]
Yes this will work.

Thank you

**Comment by philals** [comment]
Excellent. If you make the changes we can accept the PR.

**Comment by MJMortimer** [comment]
Duplicate of #228

**Pull request closed without merging**
