### PR TITLE
Demonstration of making wrapper testable

### PR DESCRIPTION
**Pull request by MatthewSteeples**
Hi,

This is very much a work in progress and is a result of a conversation we've had with the API team about making this wrapper more testable. Currently it's very tightly coupled and to include it in your unit-tested code you either need to mock out some very low level items or make your own wrapper for the wrapper.

I've made a start here on Journals showing what we think the library could look like. It doesn't break any of the behaviours of the library, and is source-compatible (though not binary compatible - you will need to recompile with the new library you can't just drop it into the folder).

I've only made the modifications to journals because I didn't want to venture all the way down this path only to be told that you'd prefer it to be done differently. I'd like to turn this into a bit of a discussion about how best to proceed with this, and it's something we're looking at implementing very soon.

I'm sorry about the whitespace changes. I can't work out what's different in the configuration of this project compared to the rest that I work on. You can view the diffs without whitespace by putting a ?w=1 on the url (https://github.com/blog/967-github-secrets).

Looking forward to the conversation :)

Regards,
Matthew

### CODE REVIEW

**Comment by MJMortimer** [comment]
Hi Matthew,

Sorry about the late reply. We have had internal discusions over the last week, and this looks like a good way going forward. 

We are wondering whether you are able to provide an example test on how you would mock out the Journals endpoint. We think it would be a good idea to include a few mocked out examples in the repository so others know how to mock it out themselves. 

You mentioned that it would be a breaking change for those not using the source, so we would like to only need to update master with the changes once, but we also would like small enough pull requests to make it easy to check over. We propose a holding branch e.g. f/interface-testing, which all the pull requests will be pointed to. We would like each pull request to have a few endpoints at a time rather than all of them. Once it's all in this new branch we can update master once and bump the major version of the wrapper nugget when it's released.

Does this sound reasonable for you?

Cheers,
Matt and Phil - API team

**Comment by MatthewSteeples** [comment]
Hi Matt and Phil,

Thanks for getting back to me. I'm happy to provide examples for it. I'm thinking at the moment the best way to provide examples will be to create a new project in the solution so it's mostly self contained. I'll need to use a Mocking framework to demonstrate it properly and the one I normally use is Moq unless you'd prefer a different one?

Having it on a separate branch sounds like a good idea so that development of it doesn't affect the main code. I'm trying to work out whether it's worth the branch staying under my account (working on the assumption that we'll be implementing it) because that means that we can rebase on the core project rather than merge in frequently (although that's only a preference of mine to rebase instead of merge).

I don't see it taking a long time to implement. Now that I've worked out the interfaces and the generics it's mostly a find and replace exercise to get everything sorted.

Regards,
Matthew

**Comment by MJMortimer** [comment]
Hey Matthew,

Sweet, sounds like we are all on the same page. 

Adding a new project in the solution is what we were thinking so that is fine. We also agree that keeping it in your fork is a great idea. We use RhinoMocks internally but using Moq is fine by us as you are familiar with it.

If you could send all your changes to this branch in your fork then we can keep trabs on the diff and see the changes. We only need a few example mock tests to use as examples so no need to go overboard.

Feel free to ping myself or @philals with any other enquiries. 

We look forward to seeing the changes.
Matt and Phil - API Team

**Comment by MatthewSteeples** [comment]
I've put a basic mock example in there. It's not quite straightforward because I wanted to re-use one of the existing examples and it's in alphabetical order.

You can see that having the `IXeroCoreApi` interface allows us to stub out any of its members (so I've done Organisation and Journals). If you run the project you'll see that it prints out the organisation name specified in the Mock and then you're better off skipping a few lines down from 21 to 32 so that you print out the count of Journals.

The only change I made to the Lister class was to make it take the interface instead of the concrete class, and everything else with it just worked (or would if we'd got the rest of the properties returning interfaces instead of classes). I left the commented out lines for Account in there so that you can see why that doesn't work (just try uncommenting them).

One thing we did for the old wrapper which we will probably do for this one is actually having 2 more implementations of the IXeroCoreApi interface. One of them will read and write to a zip file (instead of talking to the API) and another will just store the objects in memory. This means that we can run full integration tests for conversions as if we were talking to the API but without having to go through authentication, rate limiting etc.

**Comment by philals** [comment]
Thanks @MatthewSteeples . I pulled down your branch and followed the good comments and commentary in your post above. Looking good!

**Comment by MatthewSteeples** [comment]
OK. Unless @philals or @MJMortimer have any objections I'll do the rest of the properties on the interface over the next few days.

**Comment by MJMortimer** [comment]
#XeroSpeed ahead :)

**Comment by MatthewSteeples** [comment]
OK, slightly longer than planned but phase 1 of this is now complete.

I wasn't able to do 4 of the classes because they didn't inherit from the existing classes so they've been left for now. They are Allocations, Attachments, Pdf and Setup.

The changes I've made are source compatible with the existing library (and I've rebased so that it's up to date with the current version of the library) so will not require any changes to developer code but will require a recompile to release. Are you aware of any shipping libraries that have a dependence on this library?

**Comment by philals** [comment]
Thanks @MatthewSteeples. Matt and I will have a chat when we are in at work.

**Comment by philals** [comment]
Hi @MatthewSteeples thanks for doing this work.

Matt and I did a search here: http://packages.nuget.org/v1/FeedService.svc/Packages?$filter=substringof(%27Xero.API.SDK%27,%20Dependencies)%20eq%20true&$select=Id,Dependencies

And it showed no dependencies on our Nugets, so hopefully that is alright. There could still be other libraries that are not on Nuget.org but we are unaware of them.

What would be the issue of us releasing this as a release as per usual if libraries were dependant on us? Won't developers need to recompile every time we release a new version with changes.

Thanks again

**Comment by MatthewSteeples** [comment]
That's a useful NuGet link, wasn't aware you could do that!
There are 2 levels of compatibility basically, source and binary. There's a few details about it [here](http://blogs.msdn.com/b/jmstall/archive/2008/03/10/binary-vs-source-compatibility.aspx), but basically it comes down to what the scope of the change is. The changes we've introduced here basically replace most uses of classes with uses of interfaces. Because the classes were looked up at compile time, just dropping this DLL into an existing app and trying to run it would fail (because the Core class behaves differently). If you were to drop this dependency into your source code though, all of the actual contracts remain the same (as long as you're using var for variables, I'd forgotten about that bit until now). For example, the code found in the 'Counts' demo project is valid for the current release, and also works with the new version without any source changes.
If there were binaries dependent on this, they would just need to be recompiled (most likely with no changes required, or at most using var to declare some variables or returning interface types instead of concrete types if they're passing them around).

To answer your final question, if they weren't dependent on the changes and all you'd done is add stuff (new methods, new classes or new properties, or only changing method bodies) then you could get away with not recompiling because the "contract" of the assembly hasn't changed. This would also work if their library wasn't using any of the pieces you'd changed. For example, if someone only depends on the Invoice class, you could make as many breaking changes as you wanted to the Reports classes and theirs would still work.

Hope that all makes sense! :)

**Comment by philals** [comment]
Thanks for the reply @MatthewSteeples. At the same time we had a chat with NickG who mentioned much the same as you.

The plan going forward is we are going to release this as usual with a Minor version bump. If anyone is copy and pasting the DLLs then hopefully this will make them take notice.

This afternoon we will take a good look through your changes to make sure we have all our I's crossed and T's dotted. We will also flesh out the example tests and add them in, which will help us get used to the changes.

You mention Phase 1. What plans do you have for Phase 2?

Thanks Phil and Matt

**Comment by MatthewSteeples** [comment]
I still need to fix up some of the tests. The CoreTests project doesn't currently compile because there are some ambiguous type references which I'm looking into.
Phase 2 in general was going to be the tidying up of the 4 classes that didn't get done in this round (because they're implemented individually) and seeing if there were any other pieces that were relevant for this exercise.
One thing we did for the last library, although this might be more suited to live outside of the core project, is to have some (overridable) client-side validation so that while developing (or handling user input) you could see if something was likely to fail without having to hit the API. Obviously that might be difficult to keep in sync with the API as a rule with it being a moving target, but it helped us catch obvious bugs (negative value invoices was one example).

**Comment by philals** [comment]
Hi Matthew.

We think we are almost there.

I have sent a PR with a slightly cleaner and more fleshed out mocked examples. Did you have any more plans for it?

Cheers
Phil and Matt

**Comment by MatthewSteeples** [comment]
Hi Phil and Matt,

I think that's it for now. Thanks for your help in finishing it off. We're keen to get up and running with this version as soon as possible really. Do you know when you might be releasing it?

**Comment by philals** [comment]
Hi Matthew

New Zealand has a holiday this Monday, how ever we should be releasing it in Tuesday or Thursday. There is one other PR that we want to release at the same time.

Thanks Phil

**Comment by MatthewSteeples** [comment]
That's great. I just realised I'd missed something off anyway (when trying to use it in our app) so I've snuck that one in. Happy holiday :)

**Comment by philals** [comment]
Thanks Matthew for all the work. It was good to work together on this one.

**Pull request merged**
