### PR TITLE
Add Payments property to ExpenseClaim

### PR DESCRIPTION
**Pull request by fnakashima**
As suggested by Xero Developer support team, I have added Payments property to ExpenseClaims.
Tested locally and it worked fine.
Please merge the change into your master branch.

### CODE REVIEW

**Comment by philals** [comment]
Thanks for the PR!

Looks good to me. 

I have tested by creating an Expense Claim via the API. Adding a Payment in the GUI and then GET on that Expense Claim. The Payment was returned. Also check when two Payments were against the Expense Claim.

I will promote this to Master and it will be release in the next Nuget package.

Thanks
Phil - API Team

**Comment by philals** [comment]
@fnakashima Hi. I have released a new Nuget with your changes. Thanks again for the PR.

**Comment by fnakashima** [comment]
Thanks.
Actually, we use Xero API SDK Minimal version but it seems not to be updated yet.
Can you update the minimal version as well, please?

**Comment by philals** [comment]
@fnakashima Sorry about that. I have published it and checked that it's on Nuget.

**Comment by fnakashima** [comment]
Thanks. It works!

**Pull request merged**
