### PR TITLE
Add support for Associations API

### PR DESCRIPTION
**Pull request by mrrrk**
Hi

This is my first pull request (on any project) so go easy on me...

It's to add support for Associations in the Files API
[https://developer.xero.com/documentation/files-api/associations/](https://developer.xero.com/documentation/files-api/associations/)

In conjunction with files API, it will allow uploading attachments up to 10 MB, whereas the accounting attachments API limits you to 3MB.

Cheers

Mark

### CODE REVIEW

**Comment by mrrrk** [comment]
Hi

Are there any problems with this request?  I'm already using the code in my own project and it seems to be doing its job okay.  I only ask as I've just noticed the master has already moved on ahead of me...

Cheers

Mark

**Comment by MJMortimer** [comment]
Hey @mrrrk, apologies for Master already having moved ahead. We haven't had a chance to have a really good look at this just yet unfortunately. 

I have however had a brief look, and pulled it down to see how it works, and overall it looks pretty good. There are a few things that will need to be changed though. 
There is some C# 6 functionality included that will cause compiler issues for consumers that don't have the functionality available to them (I had to change the C# 6 string interpolation back to the old string.Format for example). 

Also if you could extract an interface from the allocations endpoint that would be fantastic.

I will be able to have a much better look and play around in the next few days to give a better review and leave comments on the PR as appropriate.

Nevertheless, thank you for this, it is a great contribution :)

Cheers,
Matt

**Comment by mrrrk** [comment]
Okay.  While I'm on, will my Stroustrup ('Egyptian') style brackets (as opposed to K&R style) be a problem?

**Comment by MJMortimer** [comment]
That's also a good point. Ideally it would be consistent with the rest of the code base.

**Comment by MJMortimer** [comment]
@mrrrk This has fallen out of step with master while merging other pull requests. I will checkout your branch, update it with master and recreate the PR, removing this one, and merge.

**Comment by mrrrk** [comment]
Nice one.  Cheers :o)

**Pull request closed without merging**
