### PR TITLE
Payslips api not reading ContributionType If ContributionType =SuperannuationGuaranteeCharge

### PR DESCRIPTION
**Pull request by rohitsies**
It retrieves ContributionType=null, works fine for other types. making it non nullable fixes it.
used
api.Payslips.Find(payslipId);

### CODE REVIEW

**Comment by MJMortimer** [comment]
Hey @rohitsies, thanks for the PR. 
By making it non-nullable it means it will always serialize the default value if it's not set. Does keeping it nullable but changing the datamember tag to [DataMember(EmitDefaultValue = false)] give you the result you're looking for?

**Comment by rohitsies** [comment]
Hi @MJMortimer ,
Thanks for the suggestion. 
I tried adding EmitDefaultValue=false and again ContributionType=null for ContributionType=SGC.
I see no reason for making ContributionType nullable since its a SuperannuationLine and its mandatory to have a contributiontype. I think its being made nullable by mistake while making CalculationType as nullable?

**Comment by rohitsies** [comment]
Hi @MJMortimer ,

Will you be merging this change with Main branch?

**Comment by rohitsies** [comment]
Thanks.

**Pull request merged**
