### PR TITLE
Newtonsoft.Json library upgraded from version 9.0.1 to 12.0.2

### PR DESCRIPTION
**Pull request by gabmoronintilecta**
Newtonsoft.Json library was upgraded on Nuget from version 9.0.0 to 12.0.0.

### CODE REVIEW

**Comment by dev-welli** [comment]
@gabmoronintilecta 
I have created an issue tracker for this pull request and other PRs for the Xero-Net SDK to get our developers to review them.
However, it is currently on our backlog as we currently putting more efforts into creating SDKs for OAuth 2.0 support - https://developer.xero.com/documentation/oauth2/overview

**Comment by MatthewSteeples** [comment]
@gabmoronintilecta I'm not saying it shouldn't happen, but is there a reason for this update? Dependencies of libraries usually adapt to whatever version you have installed as long as it is newer, so there's usually not a reason to update dependencies unless there are security issues in the old version or missing functionality that you want to use.

It's probably not likely with Newtonsoft.Json, but if someone was keeping their main project on version 10 (for example) for whatever reason, then they would be fine using the current version of the library but unable to use the library once your pull request was merged

Also, please note that I'm not a Xero employee, so I'm not authoritative for this repository in any way whatsoever 😄

**Comment by MJMortimer** [comment]
Hey @gabmoronintilecta, at this stage we're not looking to make any changes that are deemed unnecessary as we move towards our OAuth2.0 SDKs and support for OAuth1.0a becomes deprecated. 

Can you please let me know we you'd like this change to be made?

Cheers.

**Comment by MJMortimer** [comment]
Closing this due to inactivity

**Pull request closed without merging**
